### ISSUE TITLE
Not working - Blender 3.5, Windows 10

### ISSUE THREAD

**Issue by t0bif** [nukkio/Blender-Control-Render-Region#1]
Thank you very much for creating this addon. I wanted to try it out, to see if I could use it on an upcoming project. Installation works fine, but when I hit the "Render Region" button, I get the following error:

Python: Traceback (most recent call last):
  File "C:\Users\Tobi\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\control_render_regions.py", line 1290, in execute
    self.outputFolder=os.path.split( bpy.path.relpath(rnd.filepath) )[0]
  File "D:\Blender\3.5\3.5\scripts\modules\bpy\path.py", line 100, in relpath
    return "//" + _os.path.relpath(path, start)
  File "D:\Blender\3.5\3.5\python\lib\ntpath.py", line 744, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'J:'

I am using Windows 10 Pro.
Let me know if you need further information.

Thanks again!

**Comment by nukkio** [comment]
ciao
the problem occurs on Windows when the project and the output are on different disks: I tried to solve it, but I'm not sure if everything works, in my tests it seems so, but not being a real programmer I don't feel sure; try to test too, I continue with other tests.
